# Generated by Django 5.2.9 on 2025-12-30 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=10, unique=True)),
                ('gmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EntryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='api.userentry')),
            ],
        ),
    ]
