# Generated by Django 5.2.9 on 2026-01-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydata',
            name='algoId',
            field=models.TextField(default='default_algo'),
            preserve_default=False,
        ),
    ]
