# Generated by Django 5.2.9 on 2026-01-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entrydata_algoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydata',
            name='algoId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
