# Generated by Django 5.2.9 on 2026-01-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_entrydata_algoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydata',
            name='key',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
